/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.meldev.dao.CategoriaDao;
import com.meldev.dao.ClienteDao;
import com.meldev.dao.PedidoDao;
import com.meldev.dao.ProductoDao;
import dao.StockDao;

/**
 *
 * @author jbila
 */
public class FrmDashBoard extends javax.swing.JFrame {
    private CategoriaDao categoriaDao;
    private ProductoDao productoDao;
    private PedidoDao  pedidoDao;
    private StockDao stockDao;
    private ClienteDao clienteDao;

    /**
     * Creates new form FrmDashBoard
     */
    public FrmDashBoard() {
        initComponents();
        categoriaDao=new CategoriaDao();
        productoDao=new ProductoDao();
        pedidoDao =new PedidoDao();
        clienteDao=new ClienteDao();
        stockDao=new StockDao();
        dash();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lblProducto = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblVenda = new javax.swing.JLabel();
        lblExpirados = new javax.swing.JLabel();
        lblBaixoStock = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 250, -1));

        jPanel4.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, -1));

        jPanel5.setBackground(new java.awt.Color(51, 0, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 250, -1));

        jPanel6.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 250, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, -1));

        jPanel8.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 250, 80));

        jPanel13.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 250, -1));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 250, -1));

        jPanel11.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 250, -1));

        jPanel17.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 190, -1));

        jPanel16.setBackground(new java.awt.Color(51, 0, 51));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 190, -1));

        jPanel14.setBackground(new java.awt.Color(51, 0, 51));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 190, -1));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 250, -1));

        jPanel15.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 190, -1));

        lblProducto.setBackground(new java.awt.Color(0, 0, 0));
        lblProducto.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblProducto.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        lblProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducto.setText("Producto");
        jPanel1.add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 40));

        lblCategoria.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblCategoria.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        lblCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategoria.setText("Categoria");
        jPanel1.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 250, 40));

        lblCliente.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblCliente.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliente.setText("Cliente");
        jPanel1.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 250, 40));

        lblStock.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblStock.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        lblStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStock.setText("Stock");
        jPanel1.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 270, 70));

        lblVenda.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblVenda.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        lblVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVenda.setText("Venda");
        jPanel1.add(lblVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 270, 70));

        lblExpirados.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblExpirados.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        lblExpirados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExpirados.setText("Expirado");
        jPanel1.add(lblExpirados, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 270, 70));

        lblBaixoStock.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblBaixoStock.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        lblBaixoStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBaixoStock.setText("BaixoStock");
        jPanel1.add(lblBaixoStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 270, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDashBoard  frame=new FrmDashBoard();
              frame.setVisible(true);
              frame.setLocationRelativeTo(null);
            }
        });
    }
    private void dash(){
    
    lblCategoria.setText("Categoria:"+categoriaDao.count());
    lblProducto.setText("Producto: "+productoDao.count());
    lblCliente.setText("Cliente : "+clienteDao.count());
    lblStock.setText("Stock: "+stockDao.count());
    lblVenda.setText("Venda: "+pedidoDao.count());
    lblBaixoStock.setText("Baixo Stock: "+stockDao.getBaixoStock());
    lblExpirados.setText("Expirados: "+stockDao.getSockExpirados());
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblBaixoStock;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblExpirados;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblVenda;
    // End of variables declaration//GEN-END:variables
}
