/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author jbila
 */
public class FrmMenu2 extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu2
     */
    public FrmMenu2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHome = new javax.swing.JMenu();
        jMenuItemDashBoard = new javax.swing.JMenuItem();
        jMenuItemLogOff = new javax.swing.JMenuItem();
        jMenuVenda = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemCategoria = new javax.swing.JMenuItem();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jMenuItemProducto = new javax.swing.JMenuItem();
        jMenuItemPedido = new javax.swing.JMenuItem();
        jMenuItemPedidos = new javax.swing.JMenuItem();
        jMenuItemStock = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuContabilidade = new javax.swing.JMenu();
        jMenuConfiguracao = new javax.swing.JMenu();
        jMenuItemEmpresa = new javax.swing.JMenuItem();
        jMenuItemUtilizador = new javax.swing.JMenuItem();
        jMenuItemUnidadeMedida = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuItemRelatorioGeral = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jMenuBar1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        jMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-home-24.png"))); // NOI18N
        jMenuHome.setText("Home");
        jMenuHome.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jMenuHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenuItemDashBoard.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        jMenuItemDashBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-dashboard-layout-24.png"))); // NOI18N
        jMenuItemDashBoard.setText("dashboard");
        jMenuItemDashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDashBoardActionPerformed(evt);
            }
        });
        jMenuHome.add(jMenuItemDashBoard);

        jMenuItemLogOff.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        jMenuItemLogOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-log-out-24.png"))); // NOI18N
        jMenuItemLogOff.setText("sair");
        jMenuItemLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogOffActionPerformed(evt);
            }
        });
        jMenuHome.add(jMenuItemLogOff);

        jMenuBar1.add(jMenuHome);

        jMenuVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-purchase-24.png"))); // NOI18N
        jMenuVenda.setText("Venda");
        jMenuVenda.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        jMenuItemCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemCliente.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        jMenuItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N
        jMenuItemCliente.setText("cliente");
        jMenuItemCliente.setBorderPainted(false);
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuItemCliente);

        jMenuItemCategoria.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        jMenuItemCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-category-24.png"))); // NOI18N
        jMenuItemCategoria.setText("categoria");
        jMenuItemCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoriaActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuItemCategoria);

        jMenuItemFornecedor.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        jMenuItemFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N
        jMenuItemFornecedor.setText("fornecedor");
        jMenuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedorActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuItemFornecedor);

        jMenuItemProducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemProducto.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        jMenuItemProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-purchased-24.png"))); // NOI18N
        jMenuItemProducto.setText("producto");
        jMenuItemProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductoActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuItemProducto);

        jMenuItemPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemPedido.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        jMenuItemPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-purchase-24.png"))); // NOI18N
        jMenuItemPedido.setText("pdv");
        jMenuItemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPedidoActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuItemPedido);

        jMenuItemPedidos.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        jMenuItemPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-purchase-24.png"))); // NOI18N
        jMenuItemPedidos.setText("vendas");
        jMenuItemPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPedidosActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuItemPedidos);

        jMenuItemStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemStock.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        jMenuItemStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-stock-24.png"))); // NOI18N
        jMenuItemStock.setText("stock");
        jMenuItemStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStockActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuItemStock);
        jMenuVenda.add(jSeparator1);

        jMenuBar1.add(jMenuVenda);

        jMenuContabilidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-accounting-24.png"))); // NOI18N
        jMenuContabilidade.setText("Contabilidade");
        jMenuContabilidade.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jMenuBar1.add(jMenuContabilidade);

        jMenuConfiguracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-setting-24.png"))); // NOI18N
        jMenuConfiguracao.setText("Configuração");
        jMenuConfiguracao.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        jMenuItemEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-company-24.png"))); // NOI18N
        jMenuItemEmpresa.setText("empresa");
        jMenuItemEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmpresaActionPerformed(evt);
            }
        });
        jMenuConfiguracao.add(jMenuItemEmpresa);

        jMenuItemUtilizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N
        jMenuItemUtilizador.setText("utilizador");
        jMenuItemUtilizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUtilizadorActionPerformed(evt);
            }
        });
        jMenuConfiguracao.add(jMenuItemUtilizador);

        jMenuItemUnidadeMedida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-kg-24.png"))); // NOI18N
        jMenuItemUnidadeMedida.setText("unidade-mdedida");
        jMenuItemUnidadeMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnidadeMedidaActionPerformed(evt);
            }
        });
        jMenuConfiguracao.add(jMenuItemUnidadeMedida);

        jMenuBar1.add(jMenuConfiguracao);

        jMenuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-file-24.png"))); // NOI18N
        jMenuRelatorio.setText("Relatórios");
        jMenuRelatorio.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jMenuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatorioActionPerformed(evt);
            }
        });

        jMenuItemRelatorioGeral.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        jMenuItemRelatorioGeral.setText("geral");
        jMenuItemRelatorioGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioGeralActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemRelatorioGeral);

        jMenuBar1.add(jMenuRelatorio);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPedidosActionPerformed
        // TODO add your handling code here:
        FrmVendas.main(null);
    }//GEN-LAST:event_jMenuItemPedidosActionPerformed

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        FrmCliente.main(null);
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoriaActionPerformed
        // TODO add your handling code here:
        FrmCategoria2.main(null);
    }//GEN-LAST:event_jMenuItemCategoriaActionPerformed

    private void jMenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedorActionPerformed
        // TODO add your handling code here:
        FrmFornecedor.main(null);
    }//GEN-LAST:event_jMenuItemFornecedorActionPerformed

    private void jMenuItemProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductoActionPerformed
        // TODO add your handling code here:
        FrmProducto.main(null);
    }//GEN-LAST:event_jMenuItemProductoActionPerformed

    private void jMenuItemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPedidoActionPerformed
        // TODO add your handling code here:
        FrmVenda.main(null);
    }//GEN-LAST:event_jMenuItemPedidoActionPerformed

    private void jMenuItemStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStockActionPerformed
        // TODO add your handling code here:
        FrmStock.main(null);
    }//GEN-LAST:event_jMenuItemStockActionPerformed

    private void jMenuItemEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmpresaActionPerformed
        // TODO add your handling code here:
        FrmEmpresa.main(null);
    }//GEN-LAST:event_jMenuItemEmpresaActionPerformed

    private void jMenuItemUtilizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUtilizadorActionPerformed
        // TODO add your handling code here:
        FrmUtilizador.main(null);
    }//GEN-LAST:event_jMenuItemUtilizadorActionPerformed

    private void jMenuItemUnidadeMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnidadeMedidaActionPerformed
        // TODO add your handling code here:
        FrmUm.main(null);
    }//GEN-LAST:event_jMenuItemUnidadeMedidaActionPerformed

    private void jMenuItemDashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDashBoardActionPerformed
        // TODO add your handling code here:
        FrmDashBoard.main(null);
    }//GEN-LAST:event_jMenuItemDashBoardActionPerformed

    private void jMenuItemLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogOffActionPerformed
        if (JOptionPane.showConfirmDialog(null, "sair do Sistema", "SGV",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            FrmLogin.main(null);
            dispose();
            
        }

    }//GEN-LAST:event_jMenuItemLogOffActionPerformed

    private void jMenuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatorioActionPerformed
        
    }//GEN-LAST:event_jMenuRelatorioActionPerformed

    private void jMenuItemRelatorioGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioGeralActionPerformed
            FrmRelatorio2.main(null);

    }//GEN-LAST:event_jMenuItemRelatorioGeralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmMenu2 frame = new FrmMenu2();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuConfiguracao;
    private javax.swing.JMenu jMenuContabilidade;
    private javax.swing.JMenu jMenuHome;
    private javax.swing.JMenuItem jMenuItemCategoria;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemDashBoard;
    private javax.swing.JMenuItem jMenuItemEmpresa;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemLogOff;
    private javax.swing.JMenuItem jMenuItemPedido;
    private javax.swing.JMenuItem jMenuItemPedidos;
    private javax.swing.JMenuItem jMenuItemProducto;
    private javax.swing.JMenuItem jMenuItemRelatorioGeral;
    private javax.swing.JMenuItem jMenuItemStock;
    private javax.swing.JMenuItem jMenuItemUnidadeMedida;
    private javax.swing.JMenuItem jMenuItemUtilizador;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenu jMenuVenda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
