/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.meldev.reports.Reports;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jbila
 */
public class FrmRelatorio2 extends javax.swing.JFrame {

    private final Reports report;

    /**
     * Creates new form FrmRelatorio2
     * @throws java.sql.SQLException
     */
    public FrmRelatorio2() throws SQLException {
        initComponents();
            report = new Reports();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnClienteRepport = new javax.swing.JButton();
        btnProductoReport = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnCategoriaReport = new javax.swing.JButton();
        btnFornecedorReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(590, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 0, 0));

        btnClienteRepport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-print-24.png"))); // NOI18N
        btnClienteRepport.setText("cliente");
        btnClienteRepport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteRepportActionPerformed(evt);
            }
        });
        jPanel2.add(btnClienteRepport);

        btnProductoReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-print-24.png"))); // NOI18N
        btnProductoReport.setText("artigos");
        btnProductoReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoReportActionPerformed(evt);
            }
        });
        jPanel2.add(btnProductoReport);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-print-24.png"))); // NOI18N
        jButton3.setText("stock");
        jPanel2.add(jButton3);

        btnCategoriaReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-print-24.png"))); // NOI18N
        btnCategoriaReport.setText("categoria");
        btnCategoriaReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaReportActionPerformed(evt);
            }
        });
        jPanel2.add(btnCategoriaReport);

        btnFornecedorReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-print-24.png"))); // NOI18N
        btnFornecedorReport.setText("fornecedor");
        btnFornecedorReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorReportActionPerformed(evt);
            }
        });
        jPanel2.add(btnFornecedorReport);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductoReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoReportActionPerformed
    report.relatorioProducto();
    }//GEN-LAST:event_btnProductoReportActionPerformed

    private void btnClienteRepportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteRepportActionPerformed
      report.generateReportCliente();
 

    }//GEN-LAST:event_btnClienteRepportActionPerformed

    private void btnFornecedorReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorReportActionPerformed
        report.generateReportFornecedor();
    }//GEN-LAST:event_btnFornecedorReportActionPerformed

    private void btnCategoriaReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaReportActionPerformed
     report.generateReportCategoria();
    }//GEN-LAST:event_btnCategoriaReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    FrmRelatorio2 frame = new FrmRelatorio2();
                    frame.setVisible(true);
                    frame.setLocationRelativeTo(null);
                } catch (SQLException ex) {
                    Logger.getLogger(FrmRelatorio2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategoriaReport;
    private javax.swing.JButton btnClienteRepport;
    private javax.swing.JButton btnFornecedorReport;
    private javax.swing.JButton btnProductoReport;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
